"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    background = 'p:path'
    foreground = 'p:path-foreground'
    template = ' {{ .Path }} '
    leading_diamond = '<transparent,p:path></>'
    trailing_diamond = ''

    [blocks.segments.properties]
      style = 'agnoster'
      folder_icon = '󰉋 '
      folder_separator_icon = ' '
      home_icon = ' '

      [blocks.segments.properties.mapped_locations]
        'C:\dev\GitHub' = ' '

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    foreground = 'black'
    background = 'p:git'
    background_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}p:git-modified{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:git-diverged{{ end }}",
      "{{ if gt .Ahead 0 }}p:git-ahead{{ end }}",
      "{{ if gt .Behind 0 }}p:git-behind{{ end }}"
    ]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    powerline_symbol = ''

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    background = 'p:executiontime'
    foreground = 'p:executiontime-foreground'
    template = ' {{ .FormattedMs }} '
    powerline_symbol = ''

    [blocks.segments.properties]
      threshold = 3000.0

[transient_prompt]
  foreground = 'p:path'
  background = 'transparent'
  template = ' '

[secondary_prompt]
  foreground = 'p:path'
  background = 'transparent'
  template = '󰐕 '

[palette]
path = '#372aac'
path-foreground = '#f8fafc'
git = '#00c951'
git-modified = '#ffdf20'
git-diverged = '#fff085'
git-ahead = '#c800de'
git-behind = '#c800de'
executiontime = '#ff6900'
executiontime-foreground = '#fff7ed'
